#!/usr/bin/env bash
# Iterate every populated subdirectory of uploads/ and run
# test_single_file.py against each file. Synthetic fixtures live under
# uploads/_synthetic/ and are generated by scripts/generate_test_fixtures.py.
set -u

cd "$(dirname "$0")"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TESTING REAL FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ ! -d uploads ]; then
    echo "uploads/ directory missing — run 'mkdir -p uploads/{contracts,drawings,schedules,bim,photos,reports}'"
    exit 1
fi

total=0
ok=0
fail=0

# Walk every dir except _synthetic-already-flagged separately
for dir in uploads/contracts uploads/drawings uploads/schedules uploads/bim uploads/photos uploads/reports; do
    [ -d "$dir" ] || continue
    files=( $(find "$dir" -maxdepth 2 -type f \
        \( -name "*.pdf" -o -name "*.docx" -o -name "*.xer" \
           -o -name "*.xml" -o -name "*.dxf" -o -name "*.dwg" \
           -o -name "*.ifc" -o -name "*.jpg" -o -name "*.jpeg" \
           -o -name "*.png" -o -name "*.webp" \) ) )
    [ ${#files[@]} -eq 0 ] && continue

    echo
    echo "── $dir (${#files[@]} file(s))"
    for f in "${files[@]}"; do
        total=$((total + 1))
        if python3 test_single_file.py "$f"; then
            ok=$((ok + 1))
        else
            fail=$((fail + 1))
        fi
    done
done

# Synthetic fixtures section
if [ -d uploads/_synthetic ]; then
    echo
    echo "── uploads/_synthetic (generated fixtures)"
    for f in $(find uploads/_synthetic -maxdepth 2 -type f); do
        total=$((total + 1))
        if python3 test_single_file.py "$f"; then
            ok=$((ok + 1))
        else
            fail=$((fail + 1))
        fi
    done
fi

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TESTING COMPLETE: $ok ok, $fail failed of $total total"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
exit $fail
